### ISSUE TITLE
Revamp Auth

### ISSUE THREAD

**Issue by secona** [secona/task-tracker#6]
# Overview
I am removing Google OAuth2. I realized that OAuth2 is bigger than I thought, and I am worried that my implementation isn't secure. So, I have decided to switch it to good old email/password.

# To-dos
- [x] Remodel user
- [x] Implement register and login routes
- [x] Implement email verification
- [x] Switch to session-based authentication

# Possibilities
